M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Mon 13 Jan 2025 10:22:24 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-13T22:22:24-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1575
%
G90
G05
T1
X1.1811Y-1.1811
X1.1811Y-4.7244
X4.7244Y-4.7244
X4.7638Y-1.1811
M30
